title = "Guy J Grigsby's Tech(ish) Blog"
baseURL = "https://grigsby.dev/"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/guygrigsby\">Guy J Grigsby</a> 2020"
languageCode = "en-us"
googleAnalytics = "UA-3482923-8"

[params.info]
  homeTitle = "Guy's Blog"
  poweredby = true # Adds powered by hugo and kiss below Copyright
  related = true # Includes related articles at the bottom of the article
  codeCopy = true # Add copy button above code blocks
  taxonomiesCount = true # Add taxonomies count
  

[params.rss] # Adding this tag enables RSS feed
  includeContent = true # Includes whole content in rss
  authorName = "Guy J Grigsby" # Author full name
  authorEmail = "guy@grigsby.dev" # Author email

[params.sections_left]

[params.assets]
  customCSS = ["css/image.css"]

[params.social]
  twitter = "usernamevalid"
  github = "guygrigsby"
  email = "guy@grigsby.dev"
  linkedin = "guygrigsby"
  instagram = "guygrigsby"
  codepen = "guygrigsby"
  rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
  platforms = ["github","twitter","email"]

[params.features]
  disqusOnDemand = true  # Load Disqus comments on click

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "bw"
    tabWidth = 4

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
